import { useEffect, useMemo, useState } from 'react';
import { Building2, FileSpreadsheet, Landmark, LineChart, PlugZap, Upload, WifiOff } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Badge, Card, Field, PageHeader } from '../components/Common';
import { Modal } from '../components/Modal';
import { importBankRows, importBrokerRows, parseCsv } from '../lib/importers';
import { repo } from '../lib/db';
import type { Account } from '../types';

type ImportMode='bank'|'broker';

export function Connections(){
  const navigate=useNavigate(); const [mode,setMode]=useState<ImportMode|null>(null); const [filename,setFilename]=useState(''); const [rows,setRows]=useState<string[][]>([]); const [headers,setHeaders]=useState<string[]>([]); const [status,setStatus]=useState(''); const [accounts,setAccounts]=useState<Account[]>([]);
  const [bankMap,setBankMap]=useState({date:'',description:'',amount:'',debit:'',credit:'',account:''});
  const [brokerMap,setBrokerMap]=useState({date:'',symbol:'',side:'',quantity:'',price:'',fees:'',name:'',accountId:''});
  useEffect(()=>{repo.accounts().then(setAccounts)},[]);
  const sample=useMemo(()=>rows.slice(0,4),[rows]);
  const guess=(hs:string[], terms:string[])=>{const i=hs.findIndex(h=>terms.some(t=>h.toLowerCase().includes(t)));return i>=0?String(i):''};
  const readFile=async(file:File, m:ImportMode)=>{const text=await file.text();const parsed=parseCsv(text);if(parsed.length<2){setStatus('Could not find data rows in this file.');return;}const hs=parsed[0].map(x=>x.trim());setFilename(file.name);setHeaders(hs);setRows(parsed.slice(1));setMode(m);setStatus('');if(m==='bank')setBankMap({date:guess(hs,['date','datum','booking']),description:guess(hs,['description','omschrijving','details','merchant','mededeling']),amount:guess(hs,['amount','bedrag','montant']),debit:guess(hs,['debit','debet']),credit:guess(hs,['credit']),account:guess(hs,['account','rekening','iban'])});else setBrokerMap({date:guess(hs,['date','datum']),symbol:guess(hs,['symbol','ticker','instrument']),side:guess(hs,['side','action','type','buy/sell']),quantity:guess(hs,['quantity','qty','aantal']),price:guess(hs,['price','koers','prijs']),fees:guess(hs,['fee','commission','cost','kosten']),name:guess(hs,['name','description','instrument']),accountId:''});};
  const col=(value:string)=>value===''?undefined:Number(value);
  const doBank=async()=>{if(bankMap.date===''||bankMap.description===''||(bankMap.amount===''&&(bankMap.debit===''||bankMap.credit===''))){setStatus('Map Date + Description + Amount, or map both Debit and Credit.');return;}const n=await importBankRows(rows,{date:Number(bankMap.date),description:Number(bankMap.description),amount:col(bankMap.amount),debit:col(bankMap.debit),credit:col(bankMap.credit),account:col(bankMap.account)},filename);setStatus(`Imported ${n} rows to Review inbox.`);setMode(null);navigate('/inbox');};
  const doBroker=async()=>{if(['date','symbol','side','quantity','price'].some(k=>(brokerMap as any)[k]==='')){setStatus('Map Date, Symbol, Side, Quantity and Price.');return;}const n=await importBrokerRows(rows,{date:Number(brokerMap.date),symbol:Number(brokerMap.symbol),side:Number(brokerMap.side),quantity:Number(brokerMap.quantity),price:Number(brokerMap.price),fees:col(brokerMap.fees),name:col(brokerMap.name)},filename,brokerMap.accountId?Number(brokerMap.accountId):undefined);setStatus(`Imported ${n} broker trades.`);setMode(null);};
  const selectMap=(label:string,value:string,setter:(v:string)=>void,optional=false)=><Field label={label}><select className="select" value={value} onChange={e=>setter(e.target.value)}><option value="">{optional?'Not mapped':'Select column…'}</option>{headers.map((h,i)=><option key={i} value={i}>{h||`Column ${i+1}`}</option>)}</select></Field>;

  return <>
    <PageHeader title="Connections" subtitle="Automate what is reliable, keep every external integration optional, and preserve a fully manual fallback."/>
    {status&&<div className="notice info" style={{marginBottom:14}}>{status}</div>}
    <div className="grid three" style={{marginBottom:16}}>
      <div className="connection-card"><div className="connection-top"><div className="connection-logo"><PlugZap size={19}/></div><Badge tone="green">Active</Badge></div><h4>Market data</h4><p>The Update Market Data button uses a Yahoo-compatible quote endpoint in the Rust backend. No API key is stored. Manual prices always remain available.</p><button className="btn" onClick={()=>navigate('/investments')}>Open investments</button></div>
      <div className="connection-card"><div className="connection-top"><div className="connection-logo"><Landmark size={19}/></div><Badge tone="amber">Bridge required</Badge></div><h4>Open Banking / PSD2</h4><p>The database and connector model are ready for TrueLayer/Plaid/Tink-style read-only sync. A production OAuth bridge still requires your own provider account/client credentials and secure callback service.</p><button className="btn" disabled><WifiOff size={14}/>Not configured</button></div>
      <div className="connection-card"><div className="connection-top"><div className="connection-logo"><LineChart size={19}/></div><Badge tone="blue">Import ready</Badge></div><h4>Broker connections</h4><p>Use CSV import now. The adapter layer is ready to add read-only IBKR/Saxo APIs later without changing the local data model.</p><button className="btn" onClick={()=>document.getElementById('broker-file')?.click()}>Import broker CSV</button><input id="broker-file" style={{display:'none'}} type="file" accept=".csv,.txt" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0],'broker')}/></div>
    </div>
    <div className="grid two">
      <Card title="Bank transaction import" subtitle="CSV → local categorisation → Review inbox → ledger."><label className="dropzone"><input type="file" accept=".csv,.txt" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0],'bank')}/><Upload size={23}/><strong>Choose bank CSV</strong><span>Works with comma, semicolon or tab separated exports. You map columns once per import.</span></label></Card>
      <Card title="Broker trade import" subtitle="Useful for Bolero, Keytrade, DEGIRO or any broker that exports trades."><label className="dropzone"><input type="file" accept=".csv,.txt" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0],'broker')}/><FileSpreadsheet size={23}/><strong>Choose broker CSV</strong><span>Map symbol, BUY/SELL, quantity, price and fees. Missing securities are created automatically.</span></label></Card>
    </div>
    <div style={{height:16}}/>
    <Card title="Recommended automation mix"><div className="table-shell"><table><thead><tr><th>Data</th><th>V2 method</th><th>Privacy / reliability</th></tr></thead><tbody><tr><td>Bank transactions</td><td>CSV now; PSD2 bridge ready for later</td><td><Badge tone="green">Review-first</Badge></td></tr><tr><td>Bank balances</td><td>Manual now; Open Banking later</td><td><Badge>Local</Badge></td></tr><tr><td>Stocks / ETFs / crypto prices</td><td>Update Market Data</td><td><Badge tone="blue">One-click</Badge></td></tr><tr><td>IBKR / Saxo</td><td>CSV now; read-only API adapter later</td><td><Badge tone="amber">Optional API</Badge></td></tr><tr><td>Other brokers</td><td>CSV import</td><td><Badge tone="green">Robust</Badge></td></tr><tr><td>Real estate / pension</td><td>Manual periodic valuation</td><td><Badge>Local</Badge></td></tr></tbody></table></div></Card>

    <Modal open={mode==='bank'} title="Map bank CSV columns" subtitle={filename} onClose={()=>setMode(null)} width={760}><div className="form-grid three">{selectMap('Date',bankMap.date,v=>setBankMap({...bankMap,date:v}))}{selectMap('Description / merchant',bankMap.description,v=>setBankMap({...bankMap,description:v}))}{selectMap('Signed amount',bankMap.amount,v=>setBankMap({...bankMap,amount:v}),true)}{selectMap('Debit',bankMap.debit,v=>setBankMap({...bankMap,debit:v}),true)}{selectMap('Credit',bankMap.credit,v=>setBankMap({...bankMap,credit:v}),true)}{selectMap('Account / IBAN',bankMap.account,v=>setBankMap({...bankMap,account:v}),true)}</div><div style={{height:16}}/><Preview headers={headers} rows={sample}/><div className="form-actions"><button className="btn" onClick={()=>setMode(null)}>Cancel</button><button className="btn primary" onClick={doBank}>Import to review inbox</button></div></Modal>
    <Modal open={mode==='broker'} title="Map broker CSV columns" subtitle={filename} onClose={()=>setMode(null)} width={820}><div className="form-grid three">{selectMap('Date',brokerMap.date,v=>setBrokerMap({...brokerMap,date:v}))}{selectMap('Symbol / ticker',brokerMap.symbol,v=>setBrokerMap({...brokerMap,symbol:v}))}{selectMap('BUY / SELL',brokerMap.side,v=>setBrokerMap({...brokerMap,side:v}))}{selectMap('Quantity',brokerMap.quantity,v=>setBrokerMap({...brokerMap,quantity:v}))}{selectMap('Price',brokerMap.price,v=>setBrokerMap({...brokerMap,price:v}))}{selectMap('Fees',brokerMap.fees,v=>setBrokerMap({...brokerMap,fees:v}),true)}{selectMap('Security name',brokerMap.name,v=>setBrokerMap({...brokerMap,name:v}),true)}<Field label="Broker account"><select className="select" value={brokerMap.accountId} onChange={e=>setBrokerMap({...brokerMap,accountId:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution} · {a.name}</option>)}</select></Field></div><div style={{height:16}}/><Preview headers={headers} rows={sample}/><div className="form-actions"><button className="btn" onClick={()=>setMode(null)}>Cancel</button><button className="btn primary" onClick={doBroker}>Import trades</button></div></Modal>
  </>;
}

function Preview({headers,rows}:{headers:string[];rows:string[][]}){return <div className="table-shell"><table><thead><tr>{headers.slice(0,8).map((h,i)=><th key={i}>{h||`Col ${i+1}`}</th>)}</tr></thead><tbody>{rows.map((r,ri)=><tr key={ri}>{r.slice(0,8).map((x,i)=><td key={i}>{x.slice(0,40)}</td>)}</tr>)}</tbody></table></div>}
