import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Plus, RefreshCw, Target, Trash2 } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Card, EmptyState, Field, PageHeader } from '../components/Common';
import { Drawer } from '../components/Drawer';
import { Modal } from '../components/Modal';
import { execute, repo, select } from '../lib/db';
import { derivePositions } from '../lib/finance';
import { updateMarketData } from '../lib/market';
import { money, numberFmt, percent, todayIso } from '../lib/utils';
import type { Account, Dividend, InvestmentTarget, Position, Security, SecurityType, Trade, TradeSide } from '../types';

type Tab='positions'|'trades'|'dividends'|'targets';

export function Investments(){
  const [tab,setTab]=useState<Tab>('positions');
  const [securities,setSecurities]=useState<Security[]>([]); const [trades,setTrades]=useState<Trade[]>([]); const [dividends,setDividends]=useState<Dividend[]>([]); const [targets,setTargets]=useState<InvestmentTarget[]>([]); const [accounts,setAccounts]=useState<Account[]>([]);
  const [securityOpen,setSecurityOpen]=useState(false); const [tradeOpen,setTradeOpen]=useState(false); const [divOpen,setDivOpen]=useState(false); const [targetOpen,setTargetOpen]=useState(false); const [manualOpen,setManualOpen]=useState(false);
  const [selected,setSelected]=useState<Position|null>(null); const [updating,setUpdating]=useState(false); const [status,setStatus]=useState('');
  const [sform,setSform]=useState({type:'ETF' as SecurityType,name:'',ticker:'',market_symbol:'',isin:'',currency:'EUR',broker_account_id:'',current_price:0,target_weight:0});
  const [tform,setTform]=useState({security_id:'',account_id:'',date:todayIso(),side:'BUY' as TradeSide,quantity:0,price:0,fees:0,currency:'EUR',notes:''});
  const [dform,setDform]=useState({security_id:'',account_id:'',date:todayIso(),gross_amount:0,tax_amount:0,currency:'EUR',notes:''});
  const [tgform,setTgform]=useState({security_id:'',target_type:'Price below',trigger_value:0,action:'Consider buying',notes:''});
  const [mform,setMform]=useState({security_id:'',current_price:0,high_52w:0});
  const [history,setHistory]=useState<Array<{date:string;price:number}>>([]);

  const load=useCallback(async()=>{const [s,t,d,tg,a]=await Promise.all([repo.securities(),repo.trades(),repo.dividends(),repo.targets(),repo.accounts()]);setSecurities(s);setTrades(t);setDividends(d);setTargets(tg);setAccounts(a.filter(x=>x.type==='broker_cash'||x.type==='other'||x.type==='current'));},[]);
  useEffect(()=>{load();},[load]);
  const positions=useMemo(()=>derivePositions(securities,trades),[securities,trades]); const portfolio=positions.reduce((s,p)=>s+p.marketValue,0); const cost=positions.reduce((s,p)=>s+p.costBasis,0); const pnl=positions.reduce((s,p)=>s+p.unrealized+p.realized,0); const dividendsNet=dividends.reduce((s,d)=>s+d.gross_amount-d.tax_amount,0);
  const openPositions=positions.filter(p=>p.quantity>1e-10);

  const addSecurity=async()=>{if(!sform.name)return;await execute(`INSERT INTO securities(type,name,ticker,market_symbol,isin,currency,broker_account_id,current_price,target_weight) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[sform.type,sform.name,sform.ticker||null,sform.market_symbol||sform.ticker||null,sform.isin||null,sform.currency,sform.broker_account_id?Number(sform.broker_account_id):null,sform.current_price,sform.target_weight||null]);setSecurityOpen(false);await load();};
  const addTrade=async()=>{if(!tform.security_id||!tform.quantity||!tform.price)return;await execute(`INSERT INTO trades(security_id,account_id,date,side,quantity,price,fees,currency,notes,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'manual')`,[Number(tform.security_id),tform.account_id?Number(tform.account_id):null,tform.date,tform.side,Math.abs(tform.quantity),tform.price,Math.abs(tform.fees),tform.currency,tform.notes||null]);setTradeOpen(false);await load();};
  const addDividend=async()=>{if(!dform.security_id||!dform.gross_amount)return;await execute(`INSERT INTO dividends(security_id,account_id,date,gross_amount,tax_amount,currency,notes) VALUES($1,$2,$3,$4,$5,$6,$7)`,[Number(dform.security_id),dform.account_id?Number(dform.account_id):null,dform.date,dform.gross_amount,dform.tax_amount,dform.currency,dform.notes||null]);setDivOpen(false);await load();};
  const addTarget=async()=>{if(!tgform.security_id||!tgform.trigger_value)return;await execute(`INSERT INTO investment_targets(security_id,target_type,trigger_value,action,notes) VALUES($1,$2,$3,$4,$5)`,[Number(tgform.security_id),tgform.target_type,tgform.trigger_value,tgform.action,tgform.notes||null]);setTargetOpen(false);await load();};
  const updateManual=async()=>{if(!mform.security_id)return;await execute(`UPDATE securities SET current_price=$1,high_52w=$2,last_price_at=CURRENT_TIMESTAMP WHERE id=$3`,[mform.current_price,mform.high_52w||null,Number(mform.security_id)]);setManualOpen(false);await load();};
  const refresh=async()=>{setUpdating(true);setStatus('');try{const q=await updateMarketData(securities);setStatus(`Updated ${q.filter(x=>!x.error&&x.price>0).length}/${q.length} symbols. Use a Yahoo-compatible market symbol such as IWDA.AS or AAPL.`);await load();}catch(e){setStatus(`Update failed: ${String(e)}`)}finally{setUpdating(false)}};
  const showPosition=async(p:Position)=>{setSelected(p);setHistory(await select<{date:string;price:number}>('SELECT date,price FROM price_history WHERE security_id=$1 ORDER BY date',[p.security.id]));};
  const del=async(table:string,id:number)=>{if(confirm('Delete this record?')){await execute(`DELETE FROM ${table} WHERE id=$1`,[id]);await load();}};

  return <>
    <PageHeader title="Investments" subtitle="Derived positions, FIFO cost basis, realized/unrealized P/L, dividends and price targets." actions={<><button className="btn" onClick={()=>setManualOpen(true)}>Manual price</button><button className="btn" onClick={refresh} disabled={updating}><RefreshCw size={15}/>{updating?'Updating…':'Update market data'}</button><button className="btn primary" onClick={()=>setSecurityOpen(true)}><Plus size={15}/>Add security</button></>}/>
    {status&&<div className="notice info" style={{marginBottom:14}}>{status}</div>}
    <div className="kpi-grid" style={{gridTemplateColumns:'repeat(4,minmax(0,1fr))'}}><div className="kpi-card"><div className="kpi-top"><span>Portfolio value</span></div><div className="kpi-value">{money(portfolio)}</div><div className="kpi-sub">{openPositions.length} open positions</div></div><div className="kpi-card"><div className="kpi-top"><span>FIFO cost basis</span></div><div className="kpi-value">{money(cost)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Total P/L</span></div><div className={`kpi-value ${pnl>=0?'positive':'negative'}`}>{money(pnl)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Net dividends</span></div><div className="kpi-value positive">{money(dividendsNet)}</div></div></div>
    <div className="segmented" style={{marginBottom:14}}>{(['positions','trades','dividends','targets'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    {tab==='positions'&&<Card title="Portfolio" subtitle="Click a position for details and stored market history." actions={<button className="btn" onClick={()=>setTradeOpen(true)}><Plus size={14}/>Record trade</button>}>{!securities.length?<EmptyState title="No securities" description="Add an ETF, stock, crypto, bond or fund; then record BUY trades."/>:<div className="table-shell"><table><thead><tr><th>Security</th><th>Symbol</th><th className="numeric">Qty</th><th className="numeric">Price</th><th className="numeric">Value</th><th className="numeric">Cost</th><th className="numeric">P/L</th><th className="numeric">Weight</th><th className="numeric">Target</th></tr></thead><tbody>{positions.map(p=>{const w=portfolio>0?p.marketValue/portfolio*100:0;return <tr key={p.security.id} onClick={()=>showPosition(p)} style={{cursor:'pointer'}}><td><strong>{p.security.name}</strong><div className="mini">{p.security.type} · {p.security.currency}</div></td><td>{p.security.market_symbol||p.security.ticker||'—'}<div className="mini">{p.security.last_price_at?`updated ${p.security.last_price_at.slice(0,10)}`:'manual/no quote'}</div></td><td className="numeric">{numberFmt(p.quantity,4)}</td><td className="numeric">{money(p.security.current_price,p.security.currency,2)}{p.security.day_change_pct!=null&&<div className={p.security.day_change_pct>=0?'mini money-positive':'mini money-negative'}>{percent(p.security.day_change_pct)}</div>}</td><td className="numeric"><strong>{money(p.marketValue)}</strong></td><td className="numeric">{money(p.costBasis)}</td><td className={`numeric ${p.unrealized>=0?'money-positive':'money-negative'}`}><strong>{money(p.unrealized)}</strong><div className="mini">{percent(p.unrealizedPct)}</div></td><td className="numeric">{w.toFixed(1)}%</td><td className="numeric">{p.security.target_weight?`${p.security.target_weight.toFixed(1)}%`:'—'}</td></tr>})}</tbody></table></div>}</Card>}
    {tab==='trades'&&<Card title="Trades" actions={<button className="btn primary" onClick={()=>setTradeOpen(true)}><Plus size={14}/>Record trade</button>}>{!trades.length?<EmptyState title="No trades"/>:<div className="table-shell"><table><thead><tr><th>Date</th><th>Security</th><th>Side</th><th className="numeric">Quantity</th><th className="numeric">Price</th><th className="numeric">Fees</th><th></th></tr></thead><tbody>{trades.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.security_name}</td><td><Badge tone={t.side==='BUY'?'green':'red'}>{t.side}</Badge></td><td className="numeric">{numberFmt(t.quantity,5)}</td><td className="numeric">{money(t.price,t.currency,2)}</td><td className="numeric">{money(t.fees,t.currency,2)}</td><td className="numeric"><button className="icon-button" onClick={()=>del('trades',t.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</Card>}
    {tab==='dividends'&&<Card title="Dividends" actions={<button className="btn primary" onClick={()=>setDivOpen(true)}><Plus size={14}/>Add dividend</button>}>{!dividends.length?<EmptyState title="No dividends"/>:<div className="table-shell"><table><thead><tr><th>Date</th><th>Security</th><th className="numeric">Gross</th><th className="numeric">Tax</th><th className="numeric">Net</th><th></th></tr></thead><tbody>{dividends.map(d=><tr key={d.id}><td>{d.date}</td><td>{d.security_name}</td><td className="numeric">{money(d.gross_amount,d.currency,2)}</td><td className="numeric">{money(d.tax_amount,d.currency,2)}</td><td className="numeric money-positive">{money(d.gross_amount-d.tax_amount,d.currency,2)}</td><td className="numeric"><button className="icon-button" onClick={()=>del('dividends',d.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</Card>}
    {tab==='targets'&&<Card title="Entry / exit targets" subtitle="Planning prompts only; the app never places trades." actions={<button className="btn primary" onClick={()=>setTargetOpen(true)}><Target size={14}/>Add target</button>}>{!targets.length?<EmptyState title="No targets" description="Add price triggers or allocation thresholds as reminders."/>:<div>{targets.map(t=>{const s=securities.find(x=>x.id===t.security_id);return <div className="list-row" key={t.id}><div><strong>{s?.name||'Security'} · {t.target_type}</strong><p>{t.action}{t.notes?` · ${t.notes}`:''}</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><Badge tone="amber">{money(t.trigger_value,s?.currency||'EUR',2)}</Badge><button className="icon-button" onClick={()=>del('investment_targets',t.id)}><Trash2 size={14}/></button></div></div>})}</div>}</Card>}

    <Drawer open={!!selected} title={selected?.security.name||'Position'} subtitle={selected?.security.isin||selected?.security.market_symbol||selected?.security.ticker||undefined} onClose={()=>setSelected(null)}>{selected&&<><div className="grid two" style={{marginBottom:16}}><div className="kpi-card"><div className="kpi-top"><span>Market value</span></div><div className="kpi-value">{money(selected.marketValue)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Unrealized P/L</span></div><div className={`kpi-value ${selected.unrealized>=0?'positive':'negative'}`}>{money(selected.unrealized)}</div></div></div><Card title="Position details"><div className="metric-row"><span>Quantity</span><strong>{numberFmt(selected.quantity,5)}</strong></div><div className="metric-row"><span>Average FIFO cost</span><strong>{money(selected.averageCost,selected.security.currency,2)}</strong></div><div className="metric-row"><span>Current price</span><strong>{money(selected.security.current_price,selected.security.currency,2)}</strong></div><div className="metric-row"><span>52-week high</span><strong>{selected.security.high_52w?money(selected.security.high_52w,selected.security.currency,2):'—'}</strong></div><div className="metric-row"><span>Realized P/L</span><strong>{money(selected.realized)}</strong></div></Card><div style={{height:16}}/>
      <Card title="Stored price history">{history.length<2?<EmptyState title="Not enough history" description="Each market-data update stores a daily price point."/>:<div className="chart-wrap small"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="date" tick={{fontSize:9,fill:'var(--muted)'}} axisLine={false}/><YAxis domain={['auto','auto']} tick={{fontSize:9,fill:'var(--muted)'}} axisLine={false}/><Tooltip/><Area dataKey="price" type="monotone" stroke="var(--accent)" fill="var(--accent-soft)"/></AreaChart></ResponsiveContainer></div>}</Card></>}</Drawer>

    <Modal open={securityOpen} title="Add security" subtitle="Market symbol can differ from ticker; use a Yahoo-compatible symbol for automatic quotes." onClose={()=>setSecurityOpen(false)}><div className="form-grid"><Field label="Type"><select className="select" value={sform.type} onChange={e=>setSform({...sform,type:e.target.value as SecurityType})}>{['ETF','Stock','Crypto','Bond','Fund','Gold','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Name"><input className="input" value={sform.name} onChange={e=>setSform({...sform,name:e.target.value})}/></Field><Field label="Ticker"><input className="input" value={sform.ticker} onChange={e=>setSform({...sform,ticker:e.target.value.toUpperCase()})}/></Field><Field label="Market symbol" hint="Examples: IWDA.AS, IMIE.L, AAPL, BTC-EUR"><input className="input" value={sform.market_symbol} onChange={e=>setSform({...sform,market_symbol:e.target.value})}/></Field><Field label="ISIN"><input className="input" value={sform.isin} onChange={e=>setSform({...sform,isin:e.target.value})}/></Field><Field label="Currency"><input className="input" value={sform.currency} onChange={e=>setSform({...sform,currency:e.target.value.toUpperCase()})}/></Field><Field label="Broker account"><select className="select" value={sform.broker_account_id} onChange={e=>setSform({...sform,broker_account_id:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Initial/manual price"><input className="input" type="number" step="0.0001" value={sform.current_price} onChange={e=>setSform({...sform,current_price:Number(e.target.value)})}/></Field><Field label="Target portfolio weight %"><input className="input" type="number" step="0.1" value={sform.target_weight} onChange={e=>setSform({...sform,target_weight:Number(e.target.value)})}/></Field></div><div className="form-actions"><button className="btn" onClick={()=>setSecurityOpen(false)}>Cancel</button><button className="btn primary" onClick={addSecurity}>Add security</button></div></Modal>
    <Modal open={tradeOpen} title="Record trade" subtitle="FIFO cost basis is derived from BUY and SELL records." onClose={()=>setTradeOpen(false)}><div className="form-grid"><Field label="Security"><select className="select" value={tform.security_id} onChange={e=>setTform({...tform,security_id:e.target.value})}><option value="">Select…</option>{securities.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Side"><select className="select" value={tform.side} onChange={e=>setTform({...tform,side:e.target.value as TradeSide})}><option>BUY</option><option>SELL</option></select></Field><Field label="Date"><input className="input" type="date" value={tform.date} onChange={e=>setTform({...tform,date:e.target.value})}/></Field><Field label="Broker account"><select className="select" value={tform.account_id} onChange={e=>setTform({...tform,account_id:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Quantity"><input className="input" type="number" step="0.000001" value={tform.quantity} onChange={e=>setTform({...tform,quantity:Number(e.target.value)})}/></Field><Field label="Price per unit"><input className="input" type="number" step="0.000001" value={tform.price} onChange={e=>setTform({...tform,price:Number(e.target.value)})}/></Field><Field label="Fees"><input className="input" type="number" step="0.01" value={tform.fees} onChange={e=>setTform({...tform,fees:Number(e.target.value)})}/></Field><Field label="Currency"><input className="input" value={tform.currency} onChange={e=>setTform({...tform,currency:e.target.value.toUpperCase()})}/></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={tform.notes} onChange={e=>setTform({...tform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setTradeOpen(false)}>Cancel</button><button className="btn primary" onClick={addTrade}>Record trade</button></div></Modal>
    <Modal open={divOpen} title="Add dividend" onClose={()=>setDivOpen(false)}><div className="form-grid"><Field label="Security"><select className="select" value={dform.security_id} onChange={e=>setDform({...dform,security_id:e.target.value})}><option value="">Select…</option>{securities.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Date"><input className="input" type="date" value={dform.date} onChange={e=>setDform({...dform,date:e.target.value})}/></Field><Field label="Gross amount"><input className="input" type="number" value={dform.gross_amount} onChange={e=>setDform({...dform,gross_amount:Number(e.target.value)})}/></Field><Field label="Withholding tax"><input className="input" type="number" value={dform.tax_amount} onChange={e=>setDform({...dform,tax_amount:Number(e.target.value)})}/></Field><Field label="Account"><select className="select" value={dform.account_id} onChange={e=>setDform({...dform,account_id:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Currency"><input className="input" value={dform.currency} onChange={e=>setDform({...dform,currency:e.target.value.toUpperCase()})}/></Field></div><div className="form-actions"><button className="btn" onClick={()=>setDivOpen(false)}>Cancel</button><button className="btn primary" onClick={addDividend}>Add dividend</button></div></Modal>
    <Modal open={targetOpen} title="Add investment target" onClose={()=>setTargetOpen(false)}><div className="form-grid"><Field label="Security"><select className="select" value={tgform.security_id} onChange={e=>setTgform({...tgform,security_id:e.target.value})}><option value="">Select…</option>{securities.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Target type"><select className="select" value={tgform.target_type} onChange={e=>setTgform({...tgform,target_type:e.target.value})}><option>Price below</option><option>Price above</option><option>52W drawdown</option></select></Field><Field label="Trigger value"><input className="input" type="number" value={tgform.trigger_value} onChange={e=>setTgform({...tgform,trigger_value:Number(e.target.value)})}/></Field><Field label="Action"><input className="input" value={tgform.action} onChange={e=>setTgform({...tgform,action:e.target.value})}/></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={tgform.notes} onChange={e=>setTgform({...tgform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setTargetOpen(false)}>Cancel</button><button className="btn primary" onClick={addTarget}>Add target</button></div></Modal>
    <Modal open={manualOpen} title="Manual market price" subtitle="Fallback when a symbol is unavailable or you want a fully offline workflow." onClose={()=>setManualOpen(false)}><div className="form-grid"><Field label="Security"><select className="select" value={mform.security_id} onChange={e=>{const s=securities.find(x=>x.id===Number(e.target.value));setMform({security_id:e.target.value,current_price:s?.current_price||0,high_52w:s?.high_52w||0})}}><option value="">Select…</option>{securities.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Current price"><input className="input" type="number" step="0.000001" value={mform.current_price} onChange={e=>setMform({...mform,current_price:Number(e.target.value)})}/></Field><Field label="52W high"><input className="input" type="number" step="0.000001" value={mform.high_52w} onChange={e=>setMform({...mform,high_52w:Number(e.target.value)})}/></Field></div><div className="form-actions"><button className="btn" onClick={()=>setManualOpen(false)}>Cancel</button><button className="btn primary" onClick={updateManual}>Update</button></div></Modal>
  </>;
}
