import { useCallback, useEffect, useMemo, useState } from 'react';
import { Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { Card, EmptyState, Field, PageHeader, Badge } from '../components/Common';
import { Modal } from '../components/Modal';
import { execute, repo } from '../lib/db';
import { money, todayIso } from '../lib/utils';
import type { Debtor, Liability, Pension } from '../types';

export function Pensions(){
  const [pensions,setPensions]=useState<Pension[]>([]); const [liabilities,setLiabilities]=useState<Liability[]>([]); const [debtors,setDebtors]=useState<Debtor[]>([]);
  const [pOpen,setPOpen]=useState(false); const [lOpen,setLOpen]=useState(false); const [dOpen,setDOpen]=useState(false);
  const [pform,setPform]=useState({name:'',provider:'',type:'Private',total_contributed:0,current_value:0,annual_fee_pct:0,notes:''});
  const [lform,setLform]=useState({name:'',type:'Other',outstanding_balance:0,interest_pct:0,monthly_payment:0,notes:''});
  const [dform,setDform]=useState({name:'',amount:0,due_date:todayIso(),status:'open',notes:''});
  const load=useCallback(async()=>{const [p,l,d]=await Promise.all([repo.pensions(),repo.liabilities(),repo.debtors()]);setPensions(p);setLiabilities(l);setDebtors(d)},[]); useEffect(()=>{load()},[load]);
  const pensionTotal=useMemo(()=>pensions.reduce((s,p)=>s+p.current_value,0),[pensions]); const liabilityTotal=useMemo(()=>liabilities.reduce((s,l)=>s+l.outstanding_balance,0),[liabilities]); const receivableTotal=useMemo(()=>debtors.filter(d=>d.status!=='paid').reduce((s,d)=>s+d.amount,0),[debtors]);
  const saveP=async()=>{if(!pform.name)return;await execute(`INSERT INTO pensions(name,provider,type,total_contributed,current_value,annual_fee_pct,notes) VALUES($1,$2,$3,$4,$5,$6,$7)`,[pform.name,pform.provider,pform.type,pform.total_contributed,pform.current_value,pform.annual_fee_pct,pform.notes]);setPOpen(false);await load();};
  const saveL=async()=>{if(!lform.name)return;await execute(`INSERT INTO liabilities(name,type,outstanding_balance,interest_pct,monthly_payment,notes) VALUES($1,$2,$3,$4,$5,$6)`,[lform.name,lform.type,lform.outstanding_balance,lform.interest_pct,lform.monthly_payment,lform.notes]);setLOpen(false);await load();};
  const saveD=async()=>{if(!dform.name)return;await execute(`INSERT INTO debtors(name,amount,due_date,status,notes) VALUES($1,$2,$3,$4,$5)`,[dform.name,dform.amount,dform.due_date||null,dform.status,dform.notes||null]);setDOpen(false);await load();};
  const markPaid=async(id:number)=>{await execute(`UPDATE debtors SET status='paid' WHERE id=$1`,[id]);await load();};
  const del=async(table:string,id:number)=>{if(confirm('Delete this item?')){await execute(`DELETE FROM ${table} WHERE id=$1`,[id]);await load();}};
  return <>
    <PageHeader title="Pensions, debt & receivables" subtitle="Long-term pension assets, non-property liabilities, and money still owed to you." actions={<><button className="btn" onClick={()=>setDOpen(true)}><Plus size={14}/>Receivable</button><button className="btn" onClick={()=>setLOpen(true)}><Plus size={14}/>Liability</button><button className="btn primary" onClick={()=>setPOpen(true)}><Plus size={14}/>Pension plan</button></>}/>
    <div className="kpi-grid" style={{gridTemplateColumns:'repeat(3,minmax(0,1fr))'}}><div className="kpi-card"><div className="kpi-top"><span>Pension assets</span><ShieldCheck size={16}/></div><div className="kpi-value">{money(pensionTotal)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Other liabilities</span></div><div className="kpi-value negative">{money(liabilityTotal)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Receivables</span></div><div className="kpi-value positive">{money(receivableTotal)}</div></div></div>
    <div className="grid two"><Card title="Pension plans">{!pensions.length?<EmptyState title="No pension plans" description="Add private, employer, VAPZ, IPT or other pension assets."/>:<div>{pensions.map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><p>{p.provider||'No provider'} · {p.type} · fee {p.annual_fee_pct.toFixed(2)}%</p></div><div style={{display:'flex',alignItems:'center',gap:8}}><div className="numeric"><strong>{money(p.current_value)}</strong><div className="mini">contributed {money(p.total_contributed)}</div></div><button className="icon-button" onClick={()=>del('pensions',p.id)}><Trash2 size={14}/></button></div></div>)}</div>}</Card>
    <Card title="Other liabilities">{!liabilities.length?<EmptyState title="No other liabilities" description="Property mortgages belong on the Real estate page; add personal or practice debts here."/>:<div>{liabilities.map(l=><div className="list-row" key={l.id}><div><strong>{l.name}</strong><p><Badge tone="amber">{l.type}</Badge> · {l.interest_pct.toFixed(2)}% · {money(l.monthly_payment)}/mo</p></div><div style={{display:'flex',alignItems:'center',gap:8}}><strong className="money-negative">{money(l.outstanding_balance)}</strong><button className="icon-button" onClick={()=>del('liabilities',l.id)}><Trash2 size={14}/></button></div></div>)}</div>}</Card></div>
    <div style={{height:16}}/><Card title="Receivables / debtors" subtitle="Open receivables contribute to net worth until marked paid.">{!debtors.length?<EmptyState title="Nothing owed to you"/>:<div className="table-shell"><table><thead><tr><th>Name</th><th>Due</th><th>Status</th><th className="numeric">Amount</th><th></th></tr></thead><tbody>{debtors.map(d=><tr key={d.id}><td><strong>{d.name}</strong><div className="mini">{d.notes||''}</div></td><td>{d.due_date||'—'}</td><td><Badge tone={d.status==='paid'?'green':'amber'}>{d.status}</Badge></td><td className="numeric">{money(d.amount)}</td><td className="numeric">{d.status!=='paid'&&<button className="btn ghost" onClick={()=>markPaid(d.id)}>Mark paid</button>}<button className="icon-button" onClick={()=>del('debtors',d.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</Card>
    <Modal open={pOpen} title="Add pension plan" onClose={()=>setPOpen(false)}><div className="form-grid"><Field label="Plan name"><input className="input" value={pform.name} onChange={e=>setPform({...pform,name:e.target.value})}/></Field><Field label="Provider"><input className="input" value={pform.provider} onChange={e=>setPform({...pform,provider:e.target.value})}/></Field><Field label="Type"><select className="select" value={pform.type} onChange={e=>setPform({...pform,type:e.target.value})}><option>Private</option><option>Employer</option><option>VAPZ</option><option>IPT</option><option>RIZIV</option><option>Other</option></select></Field><Field label="Total contributed"><input className="input" type="number" value={pform.total_contributed} onChange={e=>setPform({...pform,total_contributed:Number(e.target.value)})}/></Field><Field label="Current value"><input className="input" type="number" value={pform.current_value} onChange={e=>setPform({...pform,current_value:Number(e.target.value)})}/></Field><Field label="Annual fee %"><input className="input" type="number" step="0.01" value={pform.annual_fee_pct} onChange={e=>setPform({...pform,annual_fee_pct:Number(e.target.value)})}/></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={pform.notes} onChange={e=>setPform({...pform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setPOpen(false)}>Cancel</button><button className="btn primary" onClick={saveP}>Add plan</button></div></Modal>
    <Modal open={lOpen} title="Add liability" onClose={()=>setLOpen(false)}><div className="form-grid"><Field label="Name"><input className="input" value={lform.name} onChange={e=>setLform({...lform,name:e.target.value})}/></Field><Field label="Type"><select className="select" value={lform.type} onChange={e=>setLform({...lform,type:e.target.value})}><option>Personal loan</option><option>Practice loan</option><option>Credit</option><option>Other</option></select></Field><Field label="Outstanding balance"><input className="input" type="number" value={lform.outstanding_balance} onChange={e=>setLform({...lform,outstanding_balance:Number(e.target.value)})}/></Field><Field label="Interest %"><input className="input" type="number" step="0.01" value={lform.interest_pct} onChange={e=>setLform({...lform,interest_pct:Number(e.target.value)})}/></Field><Field label="Monthly payment"><input className="input" type="number" value={lform.monthly_payment} onChange={e=>setLform({...lform,monthly_payment:Number(e.target.value)})}/></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={lform.notes} onChange={e=>setLform({...lform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setLOpen(false)}>Cancel</button><button className="btn primary" onClick={saveL}>Add liability</button></div></Modal>
    <Modal open={dOpen} title="Add receivable" onClose={()=>setDOpen(false)}><div className="form-grid"><Field label="Who owes you"><input className="input" value={dform.name} onChange={e=>setDform({...dform,name:e.target.value})}/></Field><Field label="Amount"><input className="input" type="number" value={dform.amount} onChange={e=>setDform({...dform,amount:Number(e.target.value)})}/></Field><Field label="Due date"><input className="input" type="date" value={dform.due_date} onChange={e=>setDform({...dform,due_date:e.target.value})}/></Field><Field label="Status"><select className="select" value={dform.status} onChange={e=>setDform({...dform,status:e.target.value})}><option value="open">Open</option><option value="paid">Paid</option></select></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={dform.notes} onChange={e=>setDform({...dform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setDOpen(false)}>Cancel</button><button className="btn primary" onClick={saveD}>Add receivable</button></div></Modal>
  </>;
}
