import { useCallback, useEffect, useMemo, useState } from 'react';
import { Plus, Target, Trash2 } from 'lucide-react';
import { Card, EmptyState, Field, PageHeader } from '../components/Common';
import { Modal } from '../components/Modal';
import { execute, repo, select } from '../lib/db';
import { money, todayIso } from '../lib/utils';
import type { Account } from '../types';

type Goal={id:number;name:string;target_amount:number;current_amount:number;target_date?:string|null;account_id?:number|null;notes?:string|null};
type Rule={id:number;drawdown_pct:number;deploy_amount:number;notes?:string|null};

export function Planning(){
  const [goals,setGoals]=useState<Goal[]>([]); const [rules,setRules]=useState<Rule[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [gOpen,setGOpen]=useState(false); const [rOpen,setROpen]=useState(false);
  const [gform,setGform]=useState({name:'',target_amount:0,current_amount:0,target_date:todayIso(),account_id:'',notes:''}); const [rform,setRform]=useState({drawdown_pct:10,deploy_amount:0,notes:''});
  const [split,setSplit]=useState({amount:0,people:2,paidBy:'1'});
  const load=useCallback(async()=>{const [g,r,a]=await Promise.all([select<Goal>('SELECT * FROM cash_goals ORDER BY target_date,name'),select<Rule>('SELECT * FROM deployment_rules ORDER BY drawdown_pct'),repo.accounts()]);setGoals(g);setRules(r);setAccounts(a)},[]); useEffect(()=>{load()},[load]);
  const saved=useMemo(()=>goals.reduce((s,g)=>s+g.current_amount,0),[goals]); const targets=useMemo(()=>goals.reduce((s,g)=>s+g.target_amount,0),[goals]);
  const addGoal=async()=>{if(!gform.name)return;await execute(`INSERT INTO cash_goals(name,target_amount,current_amount,target_date,account_id,notes) VALUES($1,$2,$3,$4,$5,$6)`,[gform.name,gform.target_amount,gform.current_amount,gform.target_date||null,gform.account_id?Number(gform.account_id):null,gform.notes||null]);setGOpen(false);await load();};
  const addRule=async()=>{await execute(`INSERT INTO deployment_rules(drawdown_pct,deploy_amount,notes) VALUES($1,$2,$3)`,[rform.drawdown_pct,rform.deploy_amount,rform.notes||null]);setROpen(false);await load();};
  const del=async(table:string,id:number)=>{await execute(`DELETE FROM ${table} WHERE id=$1`,[id]);await load();};
  const per=split.people>0?split.amount/split.people:0; const reimbursement=split.amount-per;
  return <>
    <PageHeader title="Planning" subtitle="Cash goals, drawdown deployment rules and simple shared-expense planning." actions={<><button className="btn" onClick={()=>setROpen(true)}><Plus size={14}/>Deployment rule</button><button className="btn primary" onClick={()=>setGOpen(true)}><Target size={14}/>Cash goal</button></>}/>
    <div className="kpi-grid" style={{gridTemplateColumns:'repeat(2,minmax(0,1fr))'}}><div className="kpi-card"><div className="kpi-top"><span>Cash goals saved</span></div><div className="kpi-value">{money(saved)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Combined targets</span></div><div className="kpi-value">{money(targets)}</div></div></div>
    <div className="grid two" style={{marginBottom:16}}><Card title="Cash goals" subtitle="Emergency fund, home deposit, tax reserve, travel or other buckets.">{!goals.length?<EmptyState title="No cash goals"/>:<div>{goals.map(g=>{const pct=g.target_amount?g.current_amount/g.target_amount*100:0;return <div className="list-row" key={g.id}><div style={{flex:1}}><div style={{display:'flex',justifyContent:'space-between',gap:12,marginBottom:7}}><strong>{g.name}</strong><span className="mini">{money(g.current_amount)} / {money(g.target_amount)} · {Math.round(pct)}%</span></div><div className="progress"><span style={{width:`${Math.min(100,pct)}%`}}/></div><p>{g.target_date?`Target ${g.target_date}`:'No target date'}{g.notes?` · ${g.notes}`:''}</p></div><button className="icon-button" onClick={()=>del('cash_goals',g.id)}><Trash2 size={14}/></button></div>})}</div>}</Card>
    <Card title="Market drawdown deployment" subtitle="A manual plan; no order is ever placed by the app.">{!rules.length?<EmptyState title="No deployment rules" description="Example: if the market is −15%, earmark €5,000 for deployment."/>:<div>{rules.map(r=><div className="list-row" key={r.id}><div><strong>At −{r.drawdown_pct.toFixed(1)}%</strong><p>{r.notes||'No note'}</p></div><div style={{display:'flex',alignItems:'center',gap:8}}><strong>{money(r.deploy_amount)}</strong><button className="icon-button" onClick={()=>del('deployment_rules',r.id)}><Trash2 size={14}/></button></div></div>)}</div>}</Card></div>
    <Card title="Split calculator" subtitle="Quick calculator; results are not stored."><div className="form-grid three"><Field label="Total amount"><input className="input" type="number" value={split.amount} onChange={e=>setSplit({...split,amount:Number(e.target.value)})}/></Field><Field label="Number of people"><input className="input" type="number" min="1" value={split.people} onChange={e=>setSplit({...split,people:Math.max(1,Number(e.target.value))})}/></Field><Field label="Paid by person"><input className="input" value={split.paidBy} onChange={e=>setSplit({...split,paidBy:e.target.value})}/></Field></div><div style={{height:14}}/><div className="metric-row"><span>Equal share per person</span><strong>{money(per,'EUR',2)}</strong></div><div className="metric-row"><span>Total reimbursement due to payer</span><strong>{money(reimbursement,'EUR',2)}</strong></div></Card>
    <Modal open={gOpen} title="Add cash goal" onClose={()=>setGOpen(false)}><div className="form-grid"><Field label="Goal name"><input className="input" value={gform.name} onChange={e=>setGform({...gform,name:e.target.value})}/></Field><Field label="Target amount"><input className="input" type="number" value={gform.target_amount} onChange={e=>setGform({...gform,target_amount:Number(e.target.value)})}/></Field><Field label="Current amount"><input className="input" type="number" value={gform.current_amount} onChange={e=>setGform({...gform,current_amount:Number(e.target.value)})}/></Field><Field label="Target date"><input className="input" type="date" value={gform.target_date} onChange={e=>setGform({...gform,target_date:e.target.value})}/></Field><Field label="Linked account"><select className="select" value={gform.account_id} onChange={e=>setGform({...gform,account_id:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={gform.notes} onChange={e=>setGform({...gform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setGOpen(false)}>Cancel</button><button className="btn primary" onClick={addGoal}>Add goal</button></div></Modal>
    <Modal open={rOpen} title="Add drawdown deployment rule" onClose={()=>setROpen(false)}><div className="form-grid"><Field label="Market drawdown %"><input className="input" type="number" min="0" value={rform.drawdown_pct} onChange={e=>setRform({...rform,drawdown_pct:Number(e.target.value)})}/></Field><Field label="Amount to deploy"><input className="input" type="number" value={rform.deploy_amount} onChange={e=>setRform({...rform,deploy_amount:Number(e.target.value)})}/></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={rform.notes} onChange={e=>setRform({...rform,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setROpen(false)}>Cancel</button><button className="btn primary" onClick={addRule}>Add rule</button></div></Modal>
  </>;
}
