import { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, Plus, Trash2 } from 'lucide-react';
import { Card, EmptyState, Field, PageHeader } from '../components/Common';
import { Modal } from '../components/Modal';
import { execute, repo } from '../lib/db';
import { money } from '../lib/utils';
import type { Property } from '../types';

const blank={name:'',address:'',type:'House',ownership_pct:100,purchase_value:0,purchase_costs:0,upgrades:0,latest_valuation:0,outstanding_debt:0,rental_income_annual:0,notes:''};
export function RealEstate(){
  const [rows,setRows]=useState<Property[]>([]); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Property|null>(null); const [form,setForm]=useState(blank);
  const load=useCallback(async()=>setRows(await repo.properties()),[]); useEffect(()=>{load();},[load]);
  const equity=useMemo(()=>rows.reduce((s,p)=>s+Math.max(0,(p.latest_valuation-p.outstanding_debt)*(p.ownership_pct/100)),0),[rows]);
  const gross=useMemo(()=>rows.reduce((s,p)=>s+p.latest_valuation*(p.ownership_pct/100),0),[rows]);
  const debt=useMemo(()=>rows.reduce((s,p)=>s+p.outstanding_debt*(p.ownership_pct/100),0),[rows]);
  const show=(p?:Property)=>{if(p){setEdit(p);setForm({name:p.name,address:p.address||'',type:p.type,ownership_pct:p.ownership_pct,purchase_value:p.purchase_value,purchase_costs:p.purchase_costs,upgrades:p.upgrades,latest_valuation:p.latest_valuation,outstanding_debt:p.outstanding_debt,rental_income_annual:p.rental_income_annual,notes:p.notes||''});}else{setEdit(null);setForm(blank)}setOpen(true)};
  const save=async()=>{if(!form.name)return;if(edit)await execute(`UPDATE properties SET name=$1,address=$2,type=$3,ownership_pct=$4,purchase_value=$5,purchase_costs=$6,upgrades=$7,latest_valuation=$8,outstanding_debt=$9,rental_income_annual=$10,notes=$11,updated_at=CURRENT_TIMESTAMP WHERE id=$12`,[form.name,form.address,form.type,form.ownership_pct,form.purchase_value,form.purchase_costs,form.upgrades,form.latest_valuation,form.outstanding_debt,form.rental_income_annual,form.notes,edit.id]);else await execute(`INSERT INTO properties(name,address,type,ownership_pct,purchase_value,purchase_costs,upgrades,latest_valuation,outstanding_debt,rental_income_annual,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[form.name,form.address,form.type,form.ownership_pct,form.purchase_value,form.purchase_costs,form.upgrades,form.latest_valuation,form.outstanding_debt,form.rental_income_annual,form.notes]);setOpen(false);await load();};
  const remove=async(id:number)=>{if(confirm('Delete this property?')){await execute('DELETE FROM properties WHERE id=$1',[id]);await load();}};
  return <>
    <PageHeader title="Real estate" subtitle="Track your proportional property value, mortgage debt, equity and rental income." actions={<button className="btn primary" onClick={()=>show()}><Plus size={15}/>Add property</button>}/>
    <div className="kpi-grid" style={{gridTemplateColumns:'repeat(3,minmax(0,1fr))'}}><div className="kpi-card"><div className="kpi-top"><span>Your property value</span><Building2 size={16}/></div><div className="kpi-value">{money(gross)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Your property debt</span></div><div className="kpi-value negative">{money(debt)}</div></div><div className="kpi-card"><div className="kpi-top"><span>Real-estate equity</span></div><div className="kpi-value">{money(equity)}</div></div></div>
    <Card title="Properties" subtitle="Equity = (valuation − property debt) × ownership %.">{!rows.length?<EmptyState title="No properties" description="Add a home, apartment, investment property or practice premises."/>:<div className="table-shell"><table><thead><tr><th>Property</th><th>Ownership</th><th className="numeric">Valuation</th><th className="numeric">Debt</th><th className="numeric">Your equity</th><th className="numeric">Annual rent</th><th></th></tr></thead><tbody>{rows.map(p=>{const own=p.ownership_pct/100;const eq=Math.max(0,(p.latest_valuation-p.outstanding_debt)*own);return <tr key={p.id}><td><strong>{p.name}</strong><div className="mini">{p.type}{p.address?` · ${p.address}`:''}</div></td><td>{p.ownership_pct.toFixed(1)}%</td><td className="numeric">{money(p.latest_valuation)}</td><td className="numeric">{money(p.outstanding_debt)}</td><td className="numeric"><strong>{money(eq)}</strong></td><td className="numeric">{money(p.rental_income_annual)}</td><td className="numeric"><button className="btn ghost" onClick={()=>show(p)}>Edit</button><button className="icon-button" onClick={()=>remove(p.id)}><Trash2 size={14}/></button></td></tr>})}</tbody></table></div>}</Card>
    <Modal open={open} title={edit?'Edit property':'Add property'} onClose={()=>setOpen(false)} width={720}><div className="form-grid three"><Field label="Name"><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Type"><select className="select" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>House</option><option>Apartment</option><option>Practice</option><option>Land</option><option>Other</option></select></Field><Field label="Ownership %"><input className="input" type="number" min="0" max="100" step="0.1" value={form.ownership_pct} onChange={e=>setForm({...form,ownership_pct:Number(e.target.value)})}/></Field><div className="full"><Field label="Address"><input className="input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field></div><Field label="Purchase value"><input className="input" type="number" value={form.purchase_value} onChange={e=>setForm({...form,purchase_value:Number(e.target.value)})}/></Field><Field label="Purchase costs"><input className="input" type="number" value={form.purchase_costs} onChange={e=>setForm({...form,purchase_costs:Number(e.target.value)})}/></Field><Field label="Cumulative upgrades"><input className="input" type="number" value={form.upgrades} onChange={e=>setForm({...form,upgrades:Number(e.target.value)})}/></Field><Field label="Latest valuation"><input className="input" type="number" value={form.latest_valuation} onChange={e=>setForm({...form,latest_valuation:Number(e.target.value)})}/></Field><Field label="Outstanding property debt"><input className="input" type="number" value={form.outstanding_debt} onChange={e=>setForm({...form,outstanding_debt:Number(e.target.value)})}/></Field><Field label="Annual rental income"><input className="input" type="number" value={form.rental_income_annual} onChange={e=>setForm({...form,rental_income_annual:Number(e.target.value)})}/></Field><div className="full"><Field label="Notes"><textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div></div><div className="form-actions"><button className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" onClick={save}>{edit?'Save changes':'Add property'}</button></div></Modal>
  </>;
}
